name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load version from VERSION file
        run: |
          if [ ! -f VERSION ]; then
            echo "Version: 1.0.0" > VERSION
          fi

          RAW_VERSION=$(grep -oP '\d+\.\d+\.\d+' VERSION)
          echo "Using version: $RAW_VERSION"
          echo "VERSION=$RAW_VERSION" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/kevin-test-k8s/frontend:${{ env.VERSION }}

      - name: Bump patch version and push updated VERSION
        run: |
          CURRENT=$(grep -oP '\d+\.\d+\.\d+' VERSION)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          NEXT="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "Version: $NEXT" > VERSION

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add VERSION
          git commit -m "Bump version to $NEXT"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main